/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BoardGame;

/**
 *
 * @author vazqu
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

public class GanadorJFrame extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form GanadorJFrame
     */
    public GanadorJFrame() {

        this.setContentPane(fondo);
        initComponents();
        setTitle("Pantalla Ganador");
        setSize(700, 700);
        setLocationRelativeTo(null);

        playSound("/sounds/Victoria.wav"); // Cambia por el nombre de tu archivo

    }

    public void playSound(String soundFilePath) {
        try {
            // Cargar el archivo de sonido
            AudioInputStream audioInput = AudioSystem.getAudioInputStream(getClass().getResource(soundFilePath));
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start(); // Reproducir el sonido
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new FondoPanel();
        jLabelFelicitaciones = new javax.swing.JLabel();
        jPanelbotones = new javax.swing.JPanel();
        jButtonReiniciar = new javax.swing.JButton();
        jLabelFelicitaciones1 = new javax.swing.JLabel();
        lblNombreJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(204, 0, 204));
        jPanelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelFelicitaciones.setFont(new java.awt.Font("Berlin Sans FB", 1, 48)); // NOI18N
        jLabelFelicitaciones.setForeground(new java.awt.Color(255, 255, 0));
        jLabelFelicitaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFelicitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Victoria.png"))); // NOI18N
        jLabelFelicitaciones.setToolTipText("");
        jLabelFelicitaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanelbotones.setBackground(new java.awt.Color(204, 0, 204));
        jPanelbotones.setOpaque(false);

        jButtonReiniciar.setBackground(new java.awt.Color(51, 51, 255));
        jButtonReiniciar.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButtonReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReiniciar.setText("Reiniciar");
        jButtonReiniciar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 3, true));
        jButtonReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonReiniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonReiniciarMouseExited(evt);
            }
        });

        jLabelFelicitaciones1.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabelFelicitaciones1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFelicitaciones1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFelicitaciones1.setText("GG ¡Bien jugado! Disfruta tu triunfo");

        javax.swing.GroupLayout jPanelbotonesLayout = new javax.swing.GroupLayout(jPanelbotones);
        jPanelbotones.setLayout(jPanelbotonesLayout);
        jPanelbotonesLayout.setHorizontalGroup(
            jPanelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbotonesLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabelFelicitaciones1)
                .addGap(102, 102, 102))
            .addGroup(jPanelbotonesLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButtonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelbotonesLayout.setVerticalGroup(
            jPanelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotonesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelFelicitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lblNombreJugador.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        lblNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreJugador.setText("¡Felicidades!");

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblNombreJugador))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelFelicitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelFelicitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(lblNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReiniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReiniciarMouseEntered
        // TODO add your handling code here:
        
        jButtonReiniciar.setBackground(new Color(255, 200, 100)); // Cambiar el color al pasar el mouse
        jButtonReiniciar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonReiniciarMouseEntered

    private void jButtonReiniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReiniciarMouseExited
        // TODO add your handling code here:
        jButtonReiniciar.setBackground(new Color(51, 51, 255)); // Restaurar el color original
        jButtonReiniciar.setForeground(Color.WHITE); // Restaurar color del texto
    }//GEN-LAST:event_jButtonReiniciarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GanadorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GanadorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GanadorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GanadorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GanadorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JLabel jLabelFelicitaciones;
    private javax.swing.JLabel jLabelFelicitaciones1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelbotones;
    private javax.swing.JLabel lblNombreJugador;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/images/VictoriaF.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
