/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BoardGame;

/**
 *
 * @author DELL
 */
public class PantallaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRegistro
     */
    public PantallaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldNombreRegistro = new javax.swing.JTextField();
        jButtonIntrucciones = new javax.swing.JButton();
        jButtonCreditos = new javax.swing.JButton();
        jButtonPartidasGuardadas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Ingresa tu Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 400, 40));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 120, 30));

        jTextFieldNombreRegistro.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jTextFieldNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 220, 40));

        jButtonIntrucciones.setBackground(new java.awt.Color(204, 0, 0));
        jButtonIntrucciones.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButtonIntrucciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIntrucciones.setText("Instrucciones");
        jButtonIntrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIntrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, -1, -1));

        jButtonCreditos.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCreditos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButtonCreditos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreditos.setText("Creditos");
        jButtonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 130, -1));

        jButtonPartidasGuardadas.setBackground(new java.awt.Color(204, 0, 0));
        jButtonPartidasGuardadas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButtonPartidasGuardadas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPartidasGuardadas.setText("Partidas Guardadas");
        jButtonPartidasGuardadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPartidasGuardadasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPartidasGuardadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PantallaRegistro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonIntruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntruccionesActionPerformed
        // TODO add your handling code here:
        PantallaInstrucciones instrucciones = new PantallaInstrucciones();

    // Mostrar la nueva ventana
    instrucciones.setVisible(true);

    // (Opcional) Cerrar la pantalla actual
    this.dispose();

    }//GEN-LAST:event_jButtonIntruccionesActionPerformed

    private void jButtonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditosActionPerformed
        // TODO add your handling code here:
         PantallaCreditos creditos = new PantallaCreditos();

    // Mostrar la ventana de créditos
    creditos.setVisible(true);

    // (Opcional) Cerrar la ventana actual
    this.dispose();
    }//GEN-LAST:event_jButtonCreditosActionPerformed

    private void jButtonPartidasGuardadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPartidasGuardadasActionPerformed
        // TODO add your handling code here:
        VentanaConsultaPartidas ventana = new VentanaConsultaPartidas();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonPartidasGuardadasActionPerformed

    private void jTextFieldNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreRegistroActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombreRegistro.getText();

    }//GEN-LAST:event_jTextFieldNombreRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCreditos;
    private javax.swing.JButton jButtonIntrucciones;
    private javax.swing.JButton jButtonPartidasGuardadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldNombreRegistro;
    // End of variables declaration//GEN-END:variables
}
