/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BoardGame.ui;

import BoardGame.Board;
import BoardGame.VentanaPrincipal;

/**
 *
 * @author DELL
 */
public class PantallaRegistro extends javax.swing.JPanel {
    private VentanaPrincipal ventana;
    /**
     * Creates new form PantallaRegistro
     */
    public PantallaRegistro(VentanaPrincipal ventana) {
        this.ventana = ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonInstrucciones = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonCreditos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 142, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 280, 60));

        jButton1.setBackground(new java.awt.Color(215, 215, 215));
        jButton1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Ingresa tu nombre: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 330, 40));

        jButtonInstrucciones.setBackground(new java.awt.Color(204, 0, 0));
        jButtonInstrucciones.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButtonInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInstrucciones.setText("Intrucciones");
        jButtonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstruccionesActionPerformed(evt);
            }
        });
        add(jButtonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Intrucciones");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        jButtonCreditos.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCreditos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButtonCreditos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreditos.setText("Creditos");
        jButtonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditosActionPerformed(evt);
            }
        });
        add(jButtonCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PantallaRegistro.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 1280, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // 1. Crea una instancia del JFrame Board
    Board boardFrame = new Board(); // Asume que Board tiene un constructor sin argumentos

    // 2. Haz visible el nuevo JFrame
    boardFrame.setVisible(true);

    // 3. (Opcional) Si quieres que la ventana actual (donde está jButton1) se cierre, la ocultas o la cierras.
    // Si esta es la ventana principal y no quieres que se quede abierta en segundo plano:
    //this.dispose(); // Cierra la ventana actual (donde está jButton1)

    // Si solo quieres ocultarla sin cerrarla completamente:
    // this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstruccionesActionPerformed
        // TODO add your handling code here:
        ventana.mostrarPantalla("instrucciones");
    }//GEN-LAST:event_jButtonInstruccionesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditosActionPerformed
        // TODO add your handling code here:
        ventana.mostrarPantalla("creditos");
    }//GEN-LAST:event_jButtonCreditosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCreditos;
    private javax.swing.JButton jButtonInstrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
