
package BoardGame.ui;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import BoardGame.VentanaPrincipal; // Importa VentanaPrincipal


public class PantallaMenu extends javax.swing.JPanel {
      private VentanaPrincipal ventana;
    
    public PantallaMenu(VentanaPrincipal ventana) {
        this.ventana = ventana;
        initComponents();
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistro.setBackground(new java.awt.Color(222, 71, 71));
        jButtonRegistro.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButtonRegistro.setText("JUGAR");
        jButtonRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });
        add(jButtonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 300, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PantallaMenu.png"))); // NOI18N
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
      ventana.mostrarPantalla("juego"); 
    }//GEN-LAST:event_jButtonRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
